# Generated by Django 5.1.1 on 2024-10-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_dentalclaim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalclaim',
            name='claim_category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dentalclaim',
            name='claim_detail',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dentalclaim',
            name='incomplete_disease_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dentalclaim',
            name='incomplete_disease_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
