# Generated by Django 4.2.16 on 2024-10-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_alter_dentalclaim_claim_category_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DentalClaim",
        ),
    ]
