# Generated by Django 5.1.1 on 2024-10-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diseasedetailcode",
            name="koicd_reference",
        ),
        migrations.AddField(
            model_name="insurancesubcategory",
            name="disease_codes",
            field=models.ManyToManyField(
                related_name="insurance_sub_categories", to="search.diseasedetailcode"
            ),
        ),
        migrations.DeleteModel(
            name="InsuranceSubCategoryDiseaseCode",
        ),
    ]
