# Generated by Django 5.1.1 on 2024-10-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_remove_diseasedetailcode_koicd_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancesubcategory",
            name="disease_sub_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="insurance_sub_categories",
                to="search.diseasesubcategory",
            ),
        ),
        migrations.AlterField(
            model_name="insurancesubcategory",
            name="disease_codes",
            field=models.ManyToManyField(
                blank=True,
                related_name="insurance_sub_categories",
                to="search.diseasedetailcode",
            ),
        ),
    ]
